//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaShop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeaShop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO CART.
        /// </summary>
        public static string addtocart {
            get {
                return ResourceManager.GetString("addtocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A GOLD FISH.
        /// </summary>
        public static string agoldfish {
            get {
                return ResourceManager.GetString("agoldfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        public static string areyousureyouwanttocancel {
            get {
                return ResourceManager.GetString("areyousureyouwanttocancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Tea.
        /// </summary>
        public static string blacktea {
            get {
                return ResourceManager.GetString("blacktea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT ONLY HURTS WHEN I TEA.
        /// </summary>
        public static string blackteadesc {
            get {
                return ResourceManager.GetString("blackteadesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camomile Tea.
        /// </summary>
        public static string camomiletea {
            get {
                return ResourceManager.GetString("camomiletea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German chamomile Matricaria recutita, or Chamomilla recutita is a hardy, self-seeding annual herb. It has long been cultivated in Germany to maximize its medicinal properties..
        /// </summary>
        public static string camomileteadesc {
            get {
                return ResourceManager.GetString("camomileteadesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type.
        /// </summary>
        public static string cardtype {
            get {
                return ResourceManager.GetString("cardtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Quantity.
        /// </summary>
        public static string changeqty {
            get {
                return ResourceManager.GetString("changeqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cofftea Tea.
        /// </summary>
        public static string coffteatea {
            get {
                return ResourceManager.GetString("coffteatea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espresso is actually a method of brewing that employs hot water “pressed” through finely ground coffee.
        /// </summary>
        public static string coffteateadesc {
            get {
                return ResourceManager.GetString("coffteateadesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number.
        /// </summary>
        public static string creditcardnumber {
            get {
                return ResourceManager.GetString("creditcardnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth:.
        /// </summary>
        public static string dateofbirth {
            get {
                return ResourceManager.GetString("dateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlgray Tea.
        /// </summary>
        public static string earlgraytea {
            get {
                return ResourceManager.GetString("earlgraytea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quintessentially British tea is typically a black tea base flavored with oil from the rind of bergamot orange, a citrus fruit with the appearance and flavor somewhere between an orange and a lemon with a little grapefruit and lime thrown in..
        /// </summary>
        public static string earlgrayteadesc {
            get {
                return ResourceManager.GetString("earlgrayteadesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string grandtotal {
            get {
                return ResourceManager.GetString("grandtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Tea.
        /// </summary>
        public static string greentea {
            get {
                return ResourceManager.GetString("greentea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green tea is a type of tea that is made from Camellia sinensis leaves that have not undergone the same withering and oxidation process used to make oolong teas and black teas..
        /// </summary>
        public static string greenteadesc {
            get {
                return ResourceManager.GetString("greenteadesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herbal Tea.
        /// </summary>
        public static string herbaltea {
            get {
                return ResourceManager.GetString("herbaltea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fruit teas are beverages made from the infusion or decoction of herbs..
        /// </summary>
        public static string herbalteadesc {
            get {
                return ResourceManager.GetString("herbalteadesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honey Lemon Tea.
        /// </summary>
        public static string honeylemontea {
            get {
                return ResourceManager.GetString("honeylemontea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put honey and lemon juice into a tea cup or mug. Add hot water and stir. Add more lemon juice, honey, or hot water to taste..
        /// </summary>
        public static string honeylemonteadesc {
            get {
                return ResourceManager.GetString("honeylemonteadesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Last Tea Order.
        /// </summary>
        public static string loadlastteaorder {
            get {
                return ResourceManager.GetString("loadlastteaorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Last User Data.
        /// </summary>
        public static string loadlastuserdata {
            get {
                return ResourceManager.GetString("loadlastuserdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Address.
        /// </summary>
        public static string mailaddress {
            get {
                return ResourceManager.GetString("mailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masala Tea.
        /// </summary>
        public static string masalatea {
            get {
                return ResourceManager.GetString("masalatea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tea beverage made by brewing black tea with a mixture of aromatic Indian spices and herbs..
        /// </summary>
        public static string masalateadesc {
            get {
                return ResourceManager.GetString("masalateadesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oolong Tea.
        /// </summary>
        public static string oolongtea {
            get {
                return ResourceManager.GetString("oolongtea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oolong tea is a product made from the leaves, buds, and stems of the Camellia sinensis plant..
        /// </summary>
        public static string oolongteadesc {
            get {
                return ResourceManager.GetString("oolongteadesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        public static string phonenumber {
            get {
                return ResourceManager.GetString("phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code:.
        /// </summary>
        public static string postalcode {
            get {
                return ResourceManager.GetString("postalcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCEED TO CHECK OUT.
        /// </summary>
        public static string proceedtocheckout {
            get {
                return ResourceManager.GetString("proceedtocheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string productname {
            get {
                return ResourceManager.GetString("productname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province:.
        /// </summary>
        public static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string purchaseorder {
            get {
                return ResourceManager.GetString("purchaseorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTY.
        /// </summary>
        public static string qty {
            get {
                return ResourceManager.GetString("qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Total:.
        /// </summary>
        public static string subtotal {
            get {
                return ResourceManager.GetString("subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax:.
        /// </summary>
        public static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tea Order Information.
        /// </summary>
        public static string teaorderinformation {
            get {
                return ResourceManager.GetString("teaorderinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tea Shop.
        /// </summary>
        public static string theteashop {
            get {
                return ResourceManager.GetString("theteashop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string userinformation {
            get {
                return ResourceManager.GetString("userinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Tea.
        /// </summary>
        public static string whitetea {
            get {
                return ResourceManager.GetString("whitetea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White tea may refer to one of several styles of tea which generally feature young or minimally processed leaves of the Camellia sinensis plant..
        /// </summary>
        public static string whiteteadesc {
            get {
                return ResourceManager.GetString("whiteteadesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
